x-common-variables: &feedbin-environment
- PORT
- RACK_ENV
- RAILS_ENV
- SECRET_KEY_BASE
- DEFAULT_URL_OPTIONS_HOST
- PUSH_URL
- FEEDBIN_URL
- FEEDBIN_HOST=$FEEDBIN_HOST,api.feedbin.com,localhost,127.0.0.1
- FORCE_SSL
- ELASTICSEARCH_URL
- MEMCACHED_HOSTS
- REDIS_URL
- DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@feedbin-postgres/feedbin_production
- EXTRACT_HOST
- EXTRACT_USER
- EXTRACT_SECRET
- CAMO_HOST=https://$CAMO_HOST
- CAMO_KEY
- SMTP_ADDRESS
- SMTP_USERNAME
- SMTP_PASSWORD
- SMTP_DOMAIN
- FROM_ADDRESS
- AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY
- AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY
- AWS_S3_BUCKET=$MINIO_BUCKET
- AWS_S3_BUCKET_FAVICONS=$MINIO_BUCKET
- AWS_S3_ENDPOINT=https://$MINIO_HOST
- AWS_S3_PATH_STYLE=true
- ENTRY_IMAGE_HOST=$MINIO_HOST
- TWITTER_KEY
- TWITTER_SECRET

services:
#  feedbin-minio-create:
#    image: minio/mc:latest
#    container_name: feedbin-minio-create
#    entrypoint: >
#      /bin/sh -c "
#      /usr/bin/mc config host add minio https://$MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY;
#      /usr/bin/mc mb minio/$MINIO_BUCKET;
#      /usr/bin/mc policy set download minio/$MINIO_BUCKET;
#      exit 0;
#      "

  feedbin-web:
    image: wrhsd/feedbin-web:latest
    container_name: feedbin-web
    environment: *feedbin-environment
    depends_on:
      - feedbin-elasticsearch
      - feedbin-memcached
      - feedbin-redis
      - feedbin-postgres
    command: bundle exec rails s --port $PORT --binding 0.0.0.0
    ports:
      - $PORT:$PORT
    restart: always

  feedbin-workers:
    image: wrhsd/feedbin-web:latest
    container_name: feedbin-workers
    environment: *feedbin-environment
    command: foreman start
    restart: always

  feedbin-elasticsearch:
    image: elasticsearch:8.2.0
    container_name: feedbin-elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - feedbin_elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always    

  feedbin-refresher:
    image: wrhsd/feedbin-refresher:latest
    environment:
      - REDIS_URL
      - TWITTER_KEY
      - TWITTER_SECRET
    container_name: feedbin-refresher
    restart: always

  feedbin-image:
    image: wrhsd/feedbin-image:latest
    environment:
      - AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY
      - AWS_S3_BUCKET=$MINIO_BUCKET
      - AWS_S3_ENDPOINT=https://$MINIO_HOST
      - AWS_S3_PATH_STYLE=true
      - REDIS_URL
    container_name: feedbin-image
    restart: always

  feedbin-extract:
    image: wrhsd/feedbin-extract:latest
    environment:
      - EXTRACT_USER=$EXTRACT_USER
      - EXTRACT_SECRET=$EXTRACT_SECRET
    container_name: feedbin-extract
    ports:
      - 3000:3000
    restart: always

  camo:
    image: wrhsd/camo:latest
    container_name: feedbin-camo
    environment:
      - PORT=8081
      - CAMO_KEY
    restart: always  
    ports:
      - 8081:8081

  feedbin-memcached:
    image: memcached:1.6-alpine
    container_name: feedbin-memcached
    restart: always

  feedbin-redis:
    image: redis:6-alpine
    container_name: feedbin-redis
    volumes:
      - feedbin_redis:/data
    command: "redis-server --appendonly yes"
    restart: always   

  feedbin-postgres:
    image: postgres:13-alpine
    container_name: feedbin-postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    restart: always
    

volumes:
  feedbin_elasticsearch:
  feedbin_redis:
  feedbin_db:
